# Generated by Django 4.2.5 on 2024-09-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_pct_alter_product_cost_alter_product_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pct',
            field=models.ImageField(blank=True, upload_to='myapp/static/img'),
        ),
    ]
